# quotes.py

quotes_list = [
    "The stars are not afraid to shine.",
    "Create beauty out of silence.",
    "Let the moonlight soften your chaos.",
    "Dreams are realities waiting to happen.",
    "Elegance is when the inside is as beautiful as the outside.",
    "In stillness, I find strength.",
    "The soul speaks in whispers and moonlight.",
    "A thought is the seed of tomorrow’s world.",
    "Soft minds create hard truths.",
    "Serenity is the rebellion of noise.",
    "Let your scars be the ink of your story.",
    "We are made of stardust and sentences.",
    "Fall in love with moments, not outcomes.",
    "Your vibe is your fingerprint on time.",
    "Hope blooms quietly in the cracks.",
    "Even shadows can glow under the right light.",
    "You are not broken, just beautifully rearranged.",
    "Simplicity is the ultimate sophistication.",
    "Grow wild and imperfectly on purpose.",
    "The sky isn't the limit—your belief is.",
    "Unwritten words weigh the heaviest.",
    "A kind word is a revolution in disguise.",
    "Let go. Let flow. Let glow.",
    "Your existence is proof of magic.",
    "There’s poetry in persistence.",
    "Peace is a posture, not a place.",
    "Flaws are fingerprints of uniqueness.",
    "The quietest people make the loudest impact.",
    "Begin again as many times as it takes.",
    "Don’t chase light. Become it."
]